server:
  port: 7001

spring:
  application:
    name: eureka-7001


eureka:
  instance:
    hostname: localhost   # 本地开发使用hostname需要在系统文件hosts内添加IP与hostname的对应
  server:
    enable-self-preservation: false   #禁用自我保护模式
    renewal-percent-threshold: 0.49  #自动续约的自我保护阈值
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
      #    service-url:
      #      defaultZone:  http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/

      #       http://${eureka.instance.hostname}:${server.port}/eureka/
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      # 集群 defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

