spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.117.193:3306/shule?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ginger416180?

##设置资源权限数据插入数据库开关
security:
  initResource: true